# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMinimumSize(QtCore.QSize(35, 0))
        self.label_10.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.userLabel = QtWidgets.QLabel(self.groupBox)
        self.userLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.userLabel.setFont(font)
        self.userLabel.setStyleSheet("QLabel{\n"
"background-color: white;\n"
"border-radius: 6px;\n"
"border-style: solid;\n"
"border-width: 1px 1px 1px 1px;\n"
"}")
        self.userLabel.setText("")
        self.userLabel.setObjectName("userLabel")
        self.horizontalLayout_5.addWidget(self.userLabel)
        self.tableBox = QtWidgets.QComboBox(self.groupBox)
        self.tableBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableBox.setMinimumContentsLength(0)
        self.tableBox.setObjectName("tableBox")
        self.horizontalLayout_5.addWidget(self.tableBox)
        self.updateButton = QtWidgets.QPushButton(self.groupBox)
        self.updateButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_5.addWidget(self.updateButton)
        self.deleteButton = QtWidgets.QPushButton(self.groupBox)
        self.deleteButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_5.addWidget(self.deleteButton)
        self.addButton = QtWidgets.QPushButton(self.groupBox)
        self.addButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_5.addWidget(self.addButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 741, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.economicLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.economicLayout.setContentsMargins(0, 0, 0, 0)
        self.economicLayout.setObjectName("economicLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.economicLayout.addWidget(self.label_4)
        self.salesBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.salesBox.setMinimum(-10000000)
        self.salesBox.setMaximum(10000000)
        self.salesBox.setObjectName("salesBox")
        self.economicLayout.addWidget(self.salesBox)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.economicLayout.addWidget(self.label_5)
        self.profitsBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.profitsBox.setMinimum(-10000000)
        self.profitsBox.setMaximum(10000000)
        self.profitsBox.setObjectName("profitsBox")
        self.economicLayout.addWidget(self.profitsBox)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.economicLayout.addWidget(self.label_6)
        self.assetsBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.assetsBox.setMinimum(-10000000)
        self.assetsBox.setMaximum(10000000)
        self.assetsBox.setObjectName("assetsBox")
        self.economicLayout.addWidget(self.assetsBox)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.economicLayout.addWidget(self.label_7)
        self.marketvalueBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.marketvalueBox.setMinimum(-10000000)
        self.marketvalueBox.setMaximum(10000000)
        self.marketvalueBox.setObjectName("marketvalueBox")
        self.economicLayout.addWidget(self.marketvalueBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 741, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.companyEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.companyEdit.setObjectName("companyEdit")
        self.horizontalLayout_2.addWidget(self.companyEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.countryEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.countryEdit.setObjectName("countryEdit")
        self.horizontalLayout_2.addWidget(self.countryEdit)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.typeEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.typeEdit.setObjectName("typeEdit")
        self.horizontalLayout_2.addWidget(self.typeEdit)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(130, 110, 141, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.yearLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.yearLayout.setContentsMargins(0, 0, 0, 0)
        self.yearLayout.setObjectName("yearLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.yearLayout.addWidget(self.label_8)
        self.yearBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.yearBox.setMinimum(1900)
        self.yearBox.setMaximum(2100)
        self.yearBox.setProperty("value", 2000)
        self.yearBox.setObjectName("yearBox")
        self.yearLayout.addWidget(self.yearBox)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(520, 110, 141, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.rankingLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.rankingLayout.setContentsMargins(0, 0, 0, 0)
        self.rankingLayout.setObjectName("rankingLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.rankingLayout.addWidget(self.label_9)
        self.rankingBox = QtWidgets.QSpinBox(self.layoutWidget3)
        self.rankingBox.setMinimum(1)
        self.rankingBox.setMaximum(2000)
        self.rankingBox.setObjectName("rankingBox")
        self.rankingLayout.addWidget(self.rankingBox)
        self.verticalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAutorization = QtWidgets.QAction(MainWindow)
        self.actionAutorization.setObjectName("actionAutorization")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInformation = QtWidgets.QAction(MainWindow)
        self.actionInformation.setObjectName("actionInformation")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionRegistration = QtWidgets.QAction(MainWindow)
        self.actionRegistration.setObjectName("actionRegistration")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAutorization)
        self.menuFile.addAction(self.actionRegistration)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionInformation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "You:"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.label_4.setText(_translate("MainWindow", "Sales:"))
        self.label_5.setText(_translate("MainWindow", "Profits:"))
        self.label_6.setText(_translate("MainWindow", "Assets:"))
        self.label_7.setText(_translate("MainWindow", "Market value:"))
        self.label.setText(_translate("MainWindow", "Company:"))
        self.label_2.setText(_translate("MainWindow", "Country:"))
        self.label_3.setText(_translate("MainWindow", "Type:"))
        self.label_8.setText(_translate("MainWindow", "Year:"))
        self.label_9.setText(_translate("MainWindow", "Ranking:"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuAbout.setTitle(_translate("MainWindow", "&About"))
        self.actionAutorization.setText(_translate("MainWindow", "Autorization"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInformation.setText(_translate("MainWindow", "Information"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionRegistration.setText(_translate("MainWindow", "Registration"))
